function command = getCommand(codeName,cfgPath,plyPath,sequence,infoName,mode)
switch mode
    case 'encode'
        command = [codeName,'.exe'...
                   ' -c ',cfgPath,'encoder.cfg'...
                   ' --uncompressedDataPath=',plyPath,sequence,'.ply'...
                   ' --compressedStreamPath=compressed.bin'...
                   ' --reconstructedDataPath=reconstruct.ply'...
                   ' >',cfgPath,infoName];
    case 'decode'
        command = [codeName,'.exe'...
                   ' -c ',cfgPath,'decoder.cfg'...
                   ' --compressedStreamPath=compressed.bin'...
                   ' --reconstructedDataPath=decoded.ply'...
                   ' >',cfgPath,infoName];
    case 'pcerror'
        command = [codeName...
                   ' -a ',plyPath,sequence,'.ply'...
                   ' -b ','decoded.ply'...
                   ' -c 1'...
                   ' --lidar=1'... % ¼ÆËãreflectance
                   ' --hausdorff=1'...% ¼ÆËãhausdorff psnr
                   ' >',cfgPath,infoName];
end